### ISSUE TITLE
Accessibility reference

### ISSUE THREAD

**Issue by TzviyaSiegman** [webmachinelearning/ethical-webmachinelearning#10]
WCAG 2.1 (https://www.w3.org/TR/WCAG21/) is usually used as the framework for considering whether something is accessible. I'm woondering why FAST is used as the reference.

**Comment by anssiko** [comment]
@michael-n-cooper which a11y document would you recommend we reference in the context of [Fairness and non-discrimination](https://webmachinelearning.github.io/ethical-webmachinelearning/#principle-2-fairness-and-non-discrimination)? Can you educate us WCAG vs FAST.

[How to do wide review](https://www.w3.org/Guide/documentreview/#how_to_get_horizontal_review) points to the FAST checklist.

**Comment by michael-n-cooper** [comment]
@anssiko In the short term I don't have the best answer. In the long term, the Framework for Accessible Specification of Technologies may be the best resource. But in its current form, it's less useful than WCAG 2.x. We are working to define systematically functional needs and user needs relating to accessibility, and intend to publish an updated draft of FAST this year that includes that. In the long term, we hope that to be the basis on which guidelines like WCAG build, and it may be the most appropriate W3C resource. But until it matures, WCAG is probably the most complete resource, albeit not structured for this situation.

Another reference I suggest is the [UN Convention on the Rights of Persons with Disabilities](https://www.ohchr.org/en/instruments-mechanisms/instruments/convention-rights-persons-disabilities). Much like the UNESCO Recommendation on the Ethics of Artificial Intelligence was used as a starting point for general ethics, the CRPD may be a good starting point for disability-specific ethics.

**Comment by anssiko** [comment]
@michael-n-cooper, thanks  for your a11y insights, we'll seek your review when we'll improve this section.

**Comment by bbcjamesfletcher** [comment]
@TzviyaSiegman @michael-n-cooper thanks for this - as @anssiko says FAST was used as the wide review points to it. Based on the above, seems to make sense to update to WCAG for now - this now reads "For further guidance on accessibility, see the Web Content Accessibility Guidelines (WCAG) 2.1, or consult the Accessible Platform Architectures (APA) Working Group." 

@anssiko i've created a pull request with this change with you as reviewer.

**Comment by shawna-slh** [comment]
> For further guidance on accessibility, see the Web Content Accessibility Guidelines (WCAG) 2.1 [[WCAG]](https://webmachinelearning.github.io/ethical-webmachinelearning/#biblio-wcag), or consult the Accessible Platform Architectures (APA) Working Group.

Thank you for encouraging accessibility and providing resources for more information.

While WCAG provides an important standard, it is not a good starting place for accessibility information. Readers new to accessibility will likely get overwhelmed and turned off. I'm not sure that "consult the Accessible Platform Architectures (APA) Working Group" is actionable?

I propose for consideration that the guidance pointed to is the W3C resource:
**[Introduction to Web Accessibility](https://www.w3.org/WAI/fundamentals/accessibility-intro/)**
-- which is published by the W3C WAI EO Working Group. That resource provides more relevant coverage related to "Fairness and non-discrimination", and links to more details.

> For guidance on digital accessibility, see the Introduction to Web Accessibility [W3C EOWG]
