### ISSUE TITLE
Add Acknowledgments section

### ISSUE THREAD

**Issue by anssiko** [webmachinelearning/ethical-webmachinelearning#12]
This is a note to self to add an acknowledgments section to the document to thank various people who have contributed to this effort during its evolution, e.g. workshop participants and facilitators, WebML WG and CG participants, and horizontal groups.

This is also a reminder to anyone lurking on this repo that we very much welcome new interested contributors to join this effort and accept contributions through GitHub issues and PRs, no matter big or small.

**Comment by bbcjamesfletcher** [comment]
@anssiko here's a list of the people involved so far, i'll leave you to add to the doc:
Commented on first draft: Christine Runnegar, Robin Berjon, Rafael Cintron, Joey Lee
Workshop 1 particpants: Stephen Beckett, Ada Rose Cannon, Anssi Kostiainen, Dan Appelquist, Matthew Atkinson, Humera Minhas, Ningxin Hu, Dominique Hazael-Massieux, Angel Li, Michael Cooper
Workshop 2 participants: Tzviya Siegman, Christine Runnegar, Joey Lee, Hadley Beeman, Jonathan Bingham, Rafael Cintron, Janina Sajka, Jason White
