### ISSUE TITLE
Add a "human rights considerations" or similar section

### ISSUE THREAD

**Issue by jyasskin** [webmachinelearning/ethical-webmachinelearning#2]
Machine learning systems have often learned biased behavior, from the [Google "gorillas" incident](https://www.theverge.com/2015/7/1/8880363/google-apologizes-photos-app-tags-two-black-people-gorillas) to [face recognition that misses black people and women](https://sitn.hms.harvard.edu/flash/2020/racial-discrimination-in-face-recognition-technology/) to [re-offending predictors that deny bail to black people](https://www.propublica.org/article/machine-bias-risk-assessments-in-criminal-sentencing).

While this spec can't prevent people from building bad ML-based systems, it can and should give some advice about how to do them better. https://datatracker.ietf.org/doc/draft-irtf-hrpc-guidelines/ proposes a standard "Human Rights Considerations" section, and this information could naturally fit there, but you could instead add a more specific section. I don't think this fits well in the existing Security or Privacy Considerations sections.

**Comment by jyasskin** [comment]
https://ainowinstitute.org/ is probably a good group to invite to participate.

Apparently [ISO SC42](https://www.iso.org/committee/6794475/x/catalogue/p/1/u/1/w/0/d/0) is working on ethical standards too.

I've also invited an appropriate Googler.

**Comment by anssiko** [comment]
@jyasskin I happened to find a connection to the AI Now Institute at New York University through my network, so we'll explore that path -- thanks for the suggestion! We're expecting a new participant to join this effort shortly (whose GH handle I don't yet have) who is well positioned to establish the AI Now Institute connection.

Anyone we could tag from ISO SC42 you know of who could help introduce the large body of documentation (behind a paywall) ISO has produced in this space?

**Comment by bbcjamesfletcher** [comment]
@jyasskin @anssiko just working through the GitHub issues before I hand the doc over - as this predates my involvement, I'm presuming the general thrust of this issue, that the spec "can and should give some advice about how to do them better" on issues such as bias etc. has been covered with the approach we have developed in the document. I'll close this issue, but if you feel the current approach misses any specific elements, please flag them.
