### ISSUE TITLE
It is unclear what the Risk TE-R1 is

### ISSUE THREAD

**Issue by xiaohk** [webmachinelearning/ethical-webmachinelearning#25]
Under section 6.6, [Risk TE-R1](https://www.w3.org/TR/webmachinelearning-ethics/#te-r1) is currently  "Issue 4: Identify risk mapping for corresponding mitigation". Does it mean this section is work-in-progress?

Thanks!

**Comment by anssiko** [comment]
That is correct. The document is work in progress and we welcome anyone interested in this space to contribute fill in these gaps.

The Risk TE-R1 could be:

>Web developers are familiar with developer tools integrated into browsers used to inspect HTML, CSS and JavaScript. These developer tools, however, do not currently understand neural network models and model inspection requires specialized tools. This complicates development and raises the barriers to entry for web developers venturing into machine learning.

Feel free to propose a better wording and add further perspectives. We're happy to [acknowledge](https://www.w3.org/TR/webmachinelearning-ethics/#acknowledgments) contributions also outside the W3C WG, including students :-)

(To make this more concrete, I think https://github.com/lutzroeder/netron style experience integrated into browser developer tools would be a nice DX.)
