### ISSUE TITLE
Types of bias

### ISSUE THREAD

**Issue by anssiko** [webmachinelearning/ethical-webmachinelearning#5]
Bias has been identified as one key ethical consideration. We have a placeholder for it here: https://webmachinelearning.github.io/ethical-webmachinelearning/#bias

I started by reviewing the types of bias, looking at how broad the scope is for someone who'd like to do exemplary work in [feature engineering](https://en.wikipedia.org/wiki/Feature_engineering) and mitigate [algorithmic bias](https://en.wikipedia.org/wiki/Algorithmic_bias).

Per Wikipedia, these are the [types of bias](https://en.wikipedia.org/wiki/Bias#Types_of_bias):
- Cognitive biases ([infographic](https://www.visualcapitalist.com/50-cognitive-biases-in-the-modern-world/))
- Conflicts of interest
- Statistical biases
- Prejudices

This is a substantial body of knowledge with all its nuances. For feature engineering purposes, it is good to be aware of these high-level concepts and have a friend who to ask for an expert's advice. This is clearly a case where a review from a cross-disciplinary team is beneficial, we cannot expect engineers to dive into cognitive science, social psychology, or behavioral economics. I think for the purposes of our document, it is good to note the high-level types of bias with pointers to good references.

Any pointers to good digestible summaries on the topic a la the infographic welcome.

**Comment by bbcjamesfletcher** [comment]
@anssiko hopefully this has now been covered in the doc with the section on bias, references provided to different types of bias. If you're happy this is covered, can you close this issue?

**Comment by anssiko** [comment]
Thanks @bbcjamesfletcher, we have now covered this on an appropriate level of abstraction and depth.
