### ISSUE TITLE
equality vs equity

### ISSUE THREAD

**Issue by TzviyaSiegman** [webmachinelearning/ethical-webmachinelearning#8]
section 3.3 speaks of fairness and equlity and mentions "biasing a system to favour people who have been historically marginalised". Consider introducing the term equity, oftening defined as the quality of being fair? In this context it might mean giving a short person a stool to stand on so that they see the same thing as a tall person.

**Comment by bbcjamesfletcher** [comment]
@TzviyaSiegman thanks for this, useful point - i've added "(this is known as equity - treating people differently on the basis of need to achieve outcomes which are fair)".

Thanks!
